### ISSUE TITLE
ERROR: Could not build wheels for commonroad-drivability-checker, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by rgu01** [CommonRoad/commonroad-drivability-checker#3]
**System description**
- OS: Ubuntu 22.04 LTS, 64bit
- CPU: Intel i5

**Conda environment description**
- pip: 24.0
- python: 3.12
- cmake: 3.22.1
- gcc/g++: 11.4

**Other common road package installed**
- commonroad.io
- commonroad.sumocr

**Error description**
Running "pip install commonroad-drivability-checker" gets the error ([error report.txt](https://github.com/CommonRoad/commonroad-drivability-checker/files/14634979/error.report.txt)):

_(...log skipped...)_
Building wheel for commonroad-drivability-checker (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1112 lines of output]
_(...log skipped...)_
        File "/tmp/pip-install-n6fix6ja/commonroad-drivability-checker_83373c1d04214c9a93b644f29613054d/setup.py", line 44, in run
          self.build_extension(ext)
        File "/tmp/pip-install-n6fix6ja/commonroad-drivability-checker_83373c1d04214c9a93b644f29613054d/setup.py", line 140, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=build_dir)
        File "/home/ron/miniconda3/envs/commonroad/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--target', 'install']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  **ERROR**: Failed building wheel for commonroad-drivability-checker
  Running setup.py clean for commonroad-drivability-checker
Failed to build commonroad-drivability-checker
**ERROR**: Could not build wheels for commonroad-drivability-checker, which is required to install pyproject.toml-based projects

**Comment by smaierhofer** [comment]
We currently only support Python 3.8-3.10. We will provide Python wheels for newer version with the next release of the tool.
